platform:ios,'8.0'
use_frameworks!

target 'BHOrder’ do
pod 'SDWebImage', '~> 4.0.0'
pod 'MJExtension', '~> 3.0.13'
pod 'MJRefresh', '~> 3.1.12'
pod 'AFNetworking', '~> 3.1.0'
pod 'IQKeyboardManager', '~> 4.0.8'
pod 'WechatOpenSDK'
end
